// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-fragrance-context.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_fragrance_context_default = defineTool2({
  name: "get_fragrance_context",
  title: "Get fragrance context",
  description: "Return recommended fragrance families and wear guidance for a given weather condition, temperature, and occasion.",
  inputSchema: {
    weather: z2.string().min(1).describe("Current weather, e.g. 'sunny', 'rainy', 'cold', 'humid'."),
    occasion: z2.string().min(1).describe("Occasion or context, e.g. 'work', 'date', 'gym', 'evening'."),
    temperatureF: z2.number().optional().describe("Ambient temperature in Fahrenheit. Defaults to 75.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ weather, occasion, temperatureF }) => {
    const temp = temperatureF ?? 75;
    const w = weather.toLowerCase();
    const o = occasion.toLowerCase();
    const families = [];
    if (temp >= 80 || w.includes("hot") || w.includes("humid") || w.includes("sun")) {
      families.push("Citrus", "Aquatic", "Fresh");
    } else if (temp <= 55 || w.includes("cold") || w.includes("snow")) {
      families.push("Woody", "Amber", "Oriental");
    } else {
      families.push("Aromatic", "Floral", "Green");
    }
    if (w.includes("rain")) families.push("Earthy");
    if (o.includes("date") || o.includes("evening") || o.includes("night")) {
      families.push("Gourmand", "Musk");
    } else if (o.includes("gym") || o.includes("sport")) {
      families.push("Clean", "Fresh");
    }
    const unique = Array.from(new Set(families));
    const guidance = `For ${occasion} in ${weather} conditions (${temp}\xB0F), lean into ${unique.slice(0, 3).join(", ")} scent profiles.`;
    return {
      content: [{ type: "text", text: guidance }],
      structuredContent: {
        weather,
        occasion,
        temperatureF: temp,
        recommendedFamilies: unique,
        guidance
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "odara-mcp",
  title: "Odara Fragrance MCP",
  version: "0.1.0",
  instructions: "Tools for the Odara fragrance oracle. Use `echo` to verify connectivity and `get_fragrance_context` to get recommended scent families for a given weather, temperature, and occasion.",
  tools: [echo_default, get_fragrance_context_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
